#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before pushing'

echo '👷 Unit tests testing your project before pushing'

# npm run test -- --watchAll=false || (
#   echo '😤🏀👋😤 Test failed here! 😤🏀👋😤 
#                 ESLint Check Failed. Make the required changes listed above, add changes and try to push again.'
#         false; 
# )
# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format or yarn format, add changes and try push again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to push again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can push
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# If everything passes... Now we can push
echo '✅✅✅✅ You win this time... I am pushing this now. ✅✅✅✅'